### ISSUE TITLE
Use new Pravega API

### ISSUE THREAD

**Issue by RaulGracia** [pravega/video-samples#10]
As part of https://github.com/pravega/pravega/pull/3126, the use of `ClientFactory` and other client-related APIs was deprecated. In PR https://github.com/pravega/pravega/pull/4417 we are removing all these deprecated APIs, which means that if you are using them your application won't compile. We need to update the samples to use the proper Pravega API.

**Comment by claudiofahey** [comment]
Completed in previous PR.
